# Generated by Django 3.2.9 on 2022-01-03 15:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loginproject', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='student',
            new_name='employee',
        ),
    ]
